layouts/_default/index.redirects
https://community.netlify.com/t/changed-behavior-in-redirects/10084
=> Fix shadowed redirects

layouts/partials/header/meta.html
See https://developers.google.com/search/docs/crawling-indexing/special-tags
=> meta.html: Use name=description instead of just itemprop

content/newsletters/pennstatealert/_index.md, content/newsletters/talkofthetown/_index.md, layouts/_default/mailchimp-page.html, layouts/_default/news.html
This fixes the nav on PS Alerts, and we can roll out this pattern more down the line.
=> mailchimp-page.html: Use nav == statecollege instead of hardcoding

src/utils/google-analytics.js
GA4 events don't work for some reason. It's not worth the time to debug it.
Old Google Analytics is reporting stale data, so I need to switch to using something else for the most popular widget. Plausible has a better API than Google, so let's use that.
=> google-analytics.js: Turn on Plausible

layouts/_default/baseof.html, layouts/partials/tw/modal-newsletter-sc.html, layouts/partials/tw/modal-ribbon.html, layouts/partials/tw/modal-sticky.html, layouts/partials/tw/modal-takeover.html, src/enhancements/modal.js, src/utils/metrics.js
- Let Almanack overwrite properties of takeover
- Fix a bug with recording subscriber status when clicking "already a member"
=> Promos: Check modal is on page before saying it should be triggered

src/utils/google-analytics.js
This did not work in production.
This reverts commit d72f62b29b46cba79cb00b9561df68ee06046a19.
=> Revert "google-analytics.js: Add GA4 hacky classes"

layouts/partials/tw/featured.html
I was looking at https://pagespeed.web.dev and it mentioned that we're lazy loading the main image on the homepage.
=> tw/featured: Don't lazy load the featured image

layouts/partials/tw/rail-most-popular.html
Because it is templated by Alpine, it doesn't receive a class from google-analytics.js.
=> rail-most-popular: Add an analytics class

layouts/shortcodes/featured/promo-contact-form.html
Form responses seem to be going to the wrong place.
=> promo-contact-form: Fix default form name

layouts/partials/newsletter/hidden.html
Some spam is getting past the Shibboleth filter. Let's add a timestamp so they can't just submit the same thing every time.
=> hidden.html: Include timestamp

layouts/partials/newsletter/hidden.html
This doesn't really matter but it will make the error logs from bots easier to read.
=> hidden.html: Don't send blank timestamp

content/newsletters/_index.md, content/newsletters/centredocumenters/_index.md, content/newsletters/investigator/_index.md, content/newsletters/palocal/_index.md, content/newsletters/papost/_index.md, content/newsletters/pennstatealert/_index.md, content/newsletters/talkofthetown/_index.md, layouts/_default/newsletters-signup.html
- Make the subheading “Get the best news from across PA straight to your inbox” a bit bigger
-  across PA straight to your inbox” a bit bigger? Reorder newsletters to: PA Post, Investigator, PA Local, Talk of the Town, Centre Documenters, Penn State Alerts
- Remove “County” from Centre Documenters
- Update Centre Documenters description
=> Requested updates for newsletter page

layouts/_default/elections-contest.html, layouts/_default/newsletters-signup.html, layouts/partials/embed/newsletter.html, layouts/partials/tw/inline-newsletter-box-sc.html, layouts/partials/tw/inline-newsletter-box.html, layouts/partials/tw/inline-newsletter-white-sc.html, layouts/partials/tw/inline-newsletter-white.html, layouts/partials/tw/modal-newsletter-sc.html, layouts/partials/tw/modal-ribbon.html, layouts/partials/tw/newsletter-box-lg.html, layouts/shortcodes/design/signups.html
I don't see how a stray quotation mark could have snuck into the URL here, but let's make them all consistent and see if that helps.
=> Newsletters: Use same action command everywhere

content/elections-2023.md, content/elections-2024.md, data/impact.json, layouts/partials/blocks/series.html, layouts/partials/header/meta.html, layouts/partials/helper/get-author.html, layouts/partials/helper/get-impact-stories.html, layouts/partials/helper/get-items.html, layouts/partials/helper/get-stories.html, layouts/partials/helper/paginator.html, layouts/partials/tw/frontpage.html, layouts/partials/tw/homepage.html, layouts/partials/tw/main-court-tool.html, layouts/partials/tw/main-transparency-tracker.html, layouts/partials/tw/rail-events.html, layouts/shortcodes/featured/related-stories.html, layouts/shortcodes/featured/series.html, layouts/shortcodes/featured/topic.html
This seems to be able to build on Hugo v118 and v123 without any changes to the deployed site. I still don't want us to upgrade now because I'm still seeing bugs in v0.123.7, like a paginated 404 page and duplicate items in the series list, but at least we will be ready if they ever work out the bugs.
See https://github.com/gohugoio/hugo/issues/12174 https://github.com/gohugoio/hugo/issues/12191 https://github.com/gohugoio/hugo/issues/12192
=> Fixes for Hugo v123

layouts/partials/helper/build-srcset.html, layouts/partials/helper/imgproxy.html, layouts/partials/tw/image-block.html, layouts/shortcodes/picture.html
The mobile app doesn't seem to be able to interpret relative URLs here, so just make them absolute by passing a new "absURL" parameter up the stack. We could just make everything absolute, but that would bloat the HTML size a little.
=> shortcodes/picture.html: Use absolute URL with imgProxy

layouts/partials/tw/image-hero.html, layouts/shortcodes/picture.html
You can't buy a phone with less than 670 device pixels across, and the app is sucking in the minimum size here for some reason.
=> shortcodes/picture.html: Drop minimum image size

layouts/partials/newsletter/hidden.html
We consider anyone who scrolls the page to not be a bot. Let's say you need to scroll and wait one second.
=> newsletter/hidden: More aggressive bot detection

layouts/shortcodes/embed/tips.html
See https://spotlightpa.org/news/2024/12/pennsylvania-medical-marijuana-top-doctor-certification/ for an example of the problem.
=> embeds/tips: Fix tip text not rending bold/italic tags

content/elections-2024-static.md, content/elections.md, content/interactives/elections-2024-static.md
We need to create a standalone static version of our Election Center page before it gets updated for the primary for award submissions.
=> Duplicate election page and give unique URL for award submissions

content/_index.md, layouts/partials/tw/frontpage.html, layouts/partials/tw/homepage.html, layouts/statecollege/list.html
Also drop the stale Talk of the Town box from State College's frontpage and rename variables to be clearer.
=> Homepage: Drop stale PA Post promo and promote PA Local

content/about/about-privacy.md, content/about/about-tos.md
There is a cascade value that disables pop ups on the about parent page.
=> Wisepops: Allow pop ups on the Terms of Service and Privacy pages

layouts/shortcodes/datawrapper.html
See https://www.datawrapper.de/blog/web-component-embedding
I'm also making a change to Almanack so we can intercept Web Component embeds from Datawrapper and turn them into `{{<datawrapper>}}` shortcodes.
=> shortcodes/datawrapper: Use Web Component, not iframe

layouts/partials/featured/social-buttons.html, tailwind.config.js
This add a Bluesky button to template articles.
Before hover:
On hover:
=> social-buttons.html: Add Bluesky button

content/newsletters/gooddayberks/_index.md, content/newsletters/howwecare/_index.md, content/newsletters/investigator/_index.md, content/newsletters/palocal/_index.md, content/newsletters/papost/_index.md, content/newsletters/pennstatealert/_index.md, content/newsletters/talkofthetown/_index.md, layouts/partials/blocks/newsletter-topper.html
Simplify the subhead on newsletter-topper by styling `strong` tags.
=> newsletter-topper: Use Tailwind sub-selector for subhead

layouts/shortcodes/flourish.html
This reverts commit 98fa8e467efcffed70ac182ae9caffa6ea89ddce.
It turns out .Ordinal counts all shortcodes, not just shortcodes of the same tag.
=> Revert "Flourish shortcode: Simpler logic"
