spotlightpa/poor-richard

content/news/2020-03-20-SPLTRACKERXX.md
layouts/dashboard/main.html
package.json

We have a giant spinner on the loose and I'm not quite sure how to bring it down to size and get the HTML for our dashboard to display properly.

Replace tracker widget with dashboard

---

assets/css/featured-tailwind.css
assets/css/main.scss
layouts/news/featured.html
layouts/partials/component/search-articles.html
layouts/partials/header/static.html
layouts/partials/newsletter/covid-landing-form.html
layouts/partials/newsletter/investigator-landing-form.html
layouts/partials/newsletter/papost-landing-form.html

Blog the change you want to see in the world.

No JS updates

---

netlify.toml

Builds are slow. Is it the caching?

Netlify: Turn off Hugo plugin

---

assets/css/tw.css
layouts/partials/tw/main.html

Should prevent overflow and speed rendering

Style: Add content-contain to article well

---

layouts/shortcodes/newsletter/palocal-form.html

Updates signup form for palocal

adds styles to palocal-form on topics page

---

layouts/partials/header/meta.html
layouts/partials/helper/new-id.html
layouts/partials/tw/nav-sc.html
layouts/partials/tw/nav.html
layouts/shortcodes/block-get.html
layouts/shortcodes/block.html
layouts/shortcodes/faq/a.html
layouts/shortcodes/faq/meta.html
layouts/shortcodes/faq/q.html

See https://discourse.gohugo.io/t/what-is-page-store/42184/5

Layout: Prefer .Page.Store to .Page.Scratch

---

layouts/_default/staff-page.html
layouts/partials/helper/get-author.html
layouts/partials/tw/donate-prefill-lg.html
prettier.config.js

- Prettier classes
- Use retina images
- Break long roles

Staff page follow up

---

layouts/_default/staff-page.html
layouts/partials/header/css-tw-merri.html
layouts/partials/header/css-tw-rale.html
yarn.lock

I think this fixes the awkward size on tablet where the cards are full width and it looks too wide. It also fixes a thing where the DL items got screwed up at some sizes.

staff-page.html: Use sub-grid, fewer magic numbers

---

layouts/partials/component/inline-cta.html

@carlmjohnson Chris requested a little more space between the cta and featured story

adds margin to inline-cta

---

layouts/partials/tw/thumb-h-story-js.html

@carlmjohnson I noticed the story-js got out of sync with thumb-h-item. This should fix it.

updates js stories in river to match thumb-h-item

---

layouts/partials/tw/featured.html

Fixes https://app.netlify.com/sites/poor-richard-spotlightpa/deploys/643832780a16590008139804

tw/featured: Fix bug when story without series/topic is featured

---

layouts/_default/page-landing.html

Adds missing icons here: https://www.spotlightpa.org/design/forms/signups

adds missing footer icons on landing page

---

assets/css/tw.css
layouts/_default/baseof.html
layouts/partials/tw/nav.html

This makes the nav more accessible and fixes issues with tabbing through the invisible items.

Nav touchups

---

layouts/embed-page/list.html
layouts/partials/header/svgs.html
layouts/partials/tw/tnd-main.html
layouts/partials/tw/tnd-sticky.html
package.json
yarn.lock

I also did some minor upgrades. 
I found out we can't move to the current Tailwind because they added in CSS logical properties with thing-s-1 for thing-start: .25rem, which conflicts with our s ("silver") colors. We'll have to rename it to g ("gray") before we do an upgrade.

Use SVG partial for copy button

---

content/series/missed-conduct/_index.md

Jeff, please merge for me this after the story is published.

Series: Add Missed Conduct

---

layouts/_default/newsletters-signup.html
src/utils/google-analytics.js

I can't get GA4 to work like old Google Analytics, so here's a hacky solution where we just add random classes to the page instead.

Analytics experiment

---

data/supporters/leadersInAction.json
data/supporters/majorDonors.json
data/supporters/members.json
data/supporters/stateCollege.json
data/supporters/stateCollegeMembers.json

Some of these had different fields from each other and a few duplicates.

Normalize donor walls

---

data/authors/Michael Berry.toml
layouts/_default/board-of-directors-page.html
layouts/partials/header/svgs.html

- sets fixed height with view more toggle on bios
- adds title to Michael Berry

requested updates:

---

content/news/2023-10-12-SPLCOURTTOOL.md
layouts/shortcodes/custom/courts-items.html
layouts/shortcodes/custom/courts-list.html
layouts/shortcodes/featured/main-takeover.html

- adds vanity url whyjudgesmatter
- increase font size on title
- decrease font size on tool hed
- adds mailto tips@ below cases

post-launch updates:

---

layouts/shortcodes/featured/scroll-video.html
layouts/shortcodes/video-item.html
src/enhancements/scroll-vimeo.js
src/esbuild/enhancements.js

This seems like it's working now, at least on desktop. I'm a little worried about if it's going to work on mobile, because it might be more strict there about requiring a touch event to trigger play.

JS: Get scroll to play working

---

src/tailwind/dev.js

Seems like leftover from before the Tailwind 3 change.

Remove unused tailwind/dev.js

---

layouts/partials/newsletter/hidden.html

Saw more bots sneak through, ugh.

hidden.html: Crank up timeout to 15 seconds

---

data/redirects.toml

Chris asked for this new donate short URL.

redirect.toml: Add /bizmember

---

data/editorsPicks.json
layouts/partials/helper/get-hp-picks.html

For technical reasons, it's harder to make this two files than just one.

Get HP picks from editorsPicks.json

---

layouts/partials/newsletter/hidden.html
layouts/shortcodes/newsletter/berks-full-form.html

People were submitting faster than 15 seconds

newsletter/berks-full-form: Set shibboleth on form focus

---

layouts/partials/tw/frontpage.html

It was showing the top of the page ad slot in the HP river.

frontpage: Really fix river ad

---

content/elections-2023.md
content/elections-2024.md
data/impact.json
layouts/partials/blocks/series.html
layouts/partials/header/meta.html
layouts/partials/helper/get-author.html
layouts/partials/helper/get-impact-stories.html
layouts/partials/helper/get-items.html
layouts/partials/helper/get-stories.html
layouts/partials/helper/paginator.html
layouts/partials/tw/frontpage.html
layouts/partials/tw/homepage.html
layouts/partials/tw/main-court-tool.html
layouts/partials/tw/main-transparency-tracker.html
layouts/partials/tw/rail-events.html
layouts/shortcodes/featured/related-stories.html
layouts/shortcodes/featured/series.html
layouts/shortcodes/featured/topic.html

Reverts spotlightpa/poor-richard#595
Elections page is messed up.

Revert "Fixes for Hugo v123"

---

layouts/partials/tw/frontpage.html
layouts/partials/tw/image-rotator.html
layouts/partials/tw/picture-rotator.html
layouts/partials/tw/promo-double.html
layouts/partials/tw/promo-single.html
layouts/partials/tw/promo-topper.html
prettier-html-ignore.rc

In the course of this I realized that the header ad and topper ad are the same now, so we should just eliminate one.

Add picture-rotator.html

---

layouts/partials/blocks/berks-full-form.html
layouts/partials/newsletter/hidden.html
layouts/shortcodes/newsletter/berks-full-form.html

Also clean up berks gaCategory

newsletter/hidden: Set human-like on scroll

---

layouts/shortcodes/embed/raw.html

This will let us override embeds in feeds and otherwise add more flexibility to how they're laid out, make embeds greppable, etc.

Shortcodes: Add embed/raw

---

config.toml
layouts/partials/header/gtm.html
layouts/partials/header/meta.html

This reverts commit 6e3227b4461d60947659b607d88497c442786ddf.
Seeing weird analytics. Undoing this to be safe.

Revert "Layout: Fix Hugo deprecation warnings (#725)"

---

content/elections-chatbot.md

This reverts commit 2fbfeb1564eac6ef3b848bfa0aaf9e823af7940d.

election-chatbot: Turn on for the week

---

content/interactives/elections-chatbot.md

This reverts commit 154266d352735cf16bb1878ddb7d86733e443f1a.

chatbot: Turn back on

---

content/about/about-staff.md

Helping prevent unnecessary calls directly to the first reporter listed

Add phone number to meet the staff page

---

content/about/friend.md
content/about/refer-a-friend.md

The idea is to have people fill out a Google Form so we can give them merch for referring friends to the newsletter.
- https://deploy-preview-821--poor-richard-spotlightpa.netlify.app/referafriend 
- https://deploy-preview-821--poor-richard-spotlightpa.netlify.app/friend

Content: Add pages for refer a friend program

---

content/support/leaders-in-action.md
data/authors/Mark Sheppard.toml

He's a Leader in Action, not on the board

Mark Sheppard: Fix

---

layouts/partials/newsletter/hidden.html

We don't need to do a timeout here if CloudFlare will run their own human-likeness tests.

newsletter/hidden.html: Simplify JS detection

---

data/awards.json

Waiting to confirm which description we want before merging

Remove duplicate award

---

content/about/about-jobs.md

Adding City/County Accountability Reporter (Reading/Berks County) job posting.
Apply link is temporarily all jobs until the specific posting is live.

Add accountability reporter job

---

layouts/_default/staff-page.html

Heather Adams isn't active anymore, so the Special Projects label doesn't have anyone under it.

Staff page: Hide unused special projects section

---

config.toml
layouts/partials/tw/inline-newsletter-form.html
layouts/shortcodes/newsletter/error-details.html
src/enhancements/newsletter.js
src/esbuild/enhancements.js

Submit newsletter with JS so we have more control over filtering out bad users. Only rolling out on archive pages for now.

Newsletters: Test new sign up JS on inline forms

---

layouts/_default/newsletters-signup.html
layouts/partials/blocks/signup-inline.html
layouts/partials/blocks/signup.html
layouts/partials/embed/newsletter.html
layouts/partials/tw/inline-newsletter-box-sc.html
layouts/partials/tw/inline-newsletter-box.html
layouts/partials/tw/inline-newsletter-form.html
src/enhancements/newsletter.js

Still have a bunch more to convert, but let's roll this out now.

Use JS for more newsletter sign ups

---

layouts/shortcodes/dewey-assistant.html

This reverts commit 6a313bc509201fc604ee572a004f079d03172c10.

Revert "shortcodes: Turn off Dewey assistant post-election"

---

content/interactives/pgh-quiz-dem.md
content/interactives/pgh-quiz-rep.md
content/interactives/pgh-quiz.md

I confused the different meanings of slug, SMDH.

Quizzes: Fix internal IDs

---

content/authors/Gabriela Martínez/_index.md
content/authors/_index.md
data/authors/Amanda Fries.toml
data/authors/Gabriela Martínez.toml
layouts/_default/author.terms.html
layouts/partials/helper/get-author.html

I changed the authors page because it has bugged me for a long time that it mixes staff with non-staff.

Author changes

---

layouts/partials/tw/frontpage.html
layouts/partials/tw/list-callout-story.html

Also link to sections from headings.

list-callout-story: Make exclusions optional

---

layouts/_default/individual-newsletter.html

individual newsletter: Fix top ad

---

src/utils/google-analytics.js

I switched the backend to use Google Analytics for the most popular list, so we don't need this anymore.

google-analytics.js: Stop reporting to Plausible
